// Official team names organized by league
// Used to populate team dropdown on the Add Card page

export const TEAMS_BY_LEAGUE = {
  NFL: [
    'Arizona Cardinals', 'Atlanta Falcons', 'Baltimore Ravens', 'Buffalo Bills',
    'Carolina Panthers', 'Chicago Bears', 'Cincinnati Bengals', 'Cleveland Browns',
    'Dallas Cowboys', 'Denver Broncos', 'Detroit Lions', 'Green Bay Packers',
    'Houston Texans', 'Indianapolis Colts', 'Jacksonville Jaguars', 'Kansas City Chiefs',
    'Las Vegas Raiders', 'Los Angeles Chargers', 'Los Angeles Rams', 'Miami Dolphins',
    'Minnesota Vikings', 'New England Patriots', 'New Orleans Saints', 'New York Giants',
    'New York Jets', 'Philadelphia Eagles', 'Pittsburgh Steelers', 'San Francisco 49ers',
    'Seattle Seahawks', 'Tampa Bay Buccaneers', 'Tennessee Titans', 'Washington Commanders',
  ],
  NBA: [
    'Atlanta Hawks', 'Boston Celtics', 'Brooklyn Nets', 'Charlotte Hornets',
    'Chicago Bulls', 'Cleveland Cavaliers', 'Dallas Mavericks', 'Denver Nuggets',
    'Detroit Pistons', 'Golden State Warriors', 'Houston Rockets', 'Indiana Pacers',
    'LA Clippers', 'Los Angeles Lakers', 'Memphis Grizzlies', 'Miami Heat',
    'Milwaukee Bucks', 'Minnesota Timberwolves', 'New Orleans Pelicans', 'New York Knicks',
    'Oklahoma City Thunder', 'Orlando Magic', 'Philadelphia 76ers', 'Phoenix Suns',
    'Portland Trail Blazers', 'Sacramento Kings', 'San Antonio Spurs', 'Toronto Raptors',
    'Utah Jazz', 'Washington Wizards',
  ],
  MLB: [
    'Arizona Diamondbacks', 'Atlanta Braves', 'Baltimore Orioles', 'Boston Red Sox',
    'Chicago Cubs', 'Chicago White Sox', 'Cincinnati Reds', 'Cleveland Guardians',
    'Colorado Rockies', 'Detroit Tigers', 'Houston Astros', 'Kansas City Royals',
    'Los Angeles Angels', 'Los Angeles Dodgers', 'Miami Marlins', 'Milwaukee Brewers',
    'Minnesota Twins', 'New York Mets', 'New York Yankees', 'Oakland Athletics',
    'Philadelphia Phillies', 'Pittsburgh Pirates', 'San Diego Padres', 'San Francisco Giants',
    'Seattle Mariners', 'St. Louis Cardinals', 'Tampa Bay Rays', 'Texas Rangers',
    'Toronto Blue Jays', 'Washington Nationals',
  ],
  NHL: [
    'Anaheim Ducks', 'Boston Bruins', 'Buffalo Sabres', 'Calgary Flames',
    'Carolina Hurricanes', 'Chicago Blackhawks', 'Colorado Avalanche', 'Columbus Blue Jackets',
    'Dallas Stars', 'Detroit Red Wings', 'Edmonton Oilers', 'Florida Panthers',
    'Los Angeles Kings', 'Minnesota Wild', 'Montreal Canadiens', 'Nashville Predators',
    'New Jersey Devils', 'New York Islanders', 'New York Rangers', 'Ottawa Senators',
    'Philadelphia Flyers', 'Pittsburgh Penguins', 'San Jose Sharks', 'Seattle Kraken',
    'St. Louis Blues', 'Tampa Bay Lightning', 'Toronto Maple Leafs', 'Utah Hockey Club',
    'Vancouver Canucks', 'Vegas Golden Knights', 'Washington Capitals', 'Winnipeg Jets',
  ],
  MLS: [
    'Atlanta United FC', 'Austin FC', 'Charlotte FC', 'Chicago Fire FC',
    'FC Cincinnati', 'Colorado Rapids', 'Columbus Crew', 'D.C. United',
    'FC Dallas', 'Houston Dynamo FC', 'Inter Miami CF', 'LA Galaxy',
    'LAFC', 'Minnesota United FC', 'CF Montréal', 'Nashville SC',
    'New England Revolution', 'New York City FC', 'New York Red Bulls', 'Orlando City SC',
    'Philadelphia Union', 'Portland Timbers', 'Real Salt Lake', 'San Jose Earthquakes',
    'Seattle Sounders FC', 'Sporting Kansas City', 'St. Louis City SC', 'Toronto FC',
    'Vancouver Whitecaps FC',
  ],
  'NCAA Football': [
    // SEC
    'Alabama Crimson Tide', 'Arkansas Razorbacks', 'Auburn Tigers', 'Florida Gators',
    'Georgia Bulldogs', 'Kentucky Wildcats', 'LSU Tigers', 'Mississippi State Bulldogs',
    'Missouri Tigers', 'Ole Miss Rebels', 'South Carolina Gamecocks', 'Tennessee Volunteers',
    'Texas Longhorns', 'Texas A&M Aggies', 'Vanderbilt Commodores',
    // Big Ten
    'Illinois Fighting Illini', 'Indiana Hoosiers', 'Iowa Hawkeyes', 'Maryland Terrapins',
    'Michigan Wolverines', 'Michigan State Spartans', 'Minnesota Golden Gophers',
    'Nebraska Cornhuskers', 'Northwestern Wildcats', 'Ohio State Buckeyes', 'Oregon Ducks',
    'Penn State Nittany Lions', 'Purdue Boilermakers', 'Rutgers Scarlet Knights',
    'UCLA Bruins', 'USC Trojans', 'Washington Huskies', 'Wisconsin Badgers',
    // Big 12
    'Arizona Wildcats', 'Arizona State Sun Devils', 'Baylor Bears', 'BYU Cougars',
    'Cincinnati Bearcats', 'Colorado Buffaloes', 'Houston Cougars', 'Iowa State Cyclones',
    'Kansas Jayhawks', 'Kansas State Wildcats', 'Oklahoma State Cowboys', 'TCU Horned Frogs',
    'Texas Tech Red Raiders', 'UCF Knights', 'Utah Utes', 'West Virginia Mountaineers',
    // ACC
    'Boston College Eagles', 'California Golden Bears', 'Clemson Tigers', 'Duke Blue Devils',
    'Florida State Seminoles', 'Georgia Tech Yellow Jackets', 'Louisville Cardinals',
    'Miami Hurricanes', 'NC State Wolfpack', 'North Carolina Tar Heels', 'Notre Dame Fighting Irish',
    'Pittsburgh Panthers', 'SMU Mustangs', 'Stanford Cardinal', 'Syracuse Orange',
    'Virginia Cavaliers', 'Virginia Tech Hokies', 'Wake Forest Demon Deacons',
    // Other notable programs
    'Air Force Falcons', 'Army Black Knights', 'Boise State Broncos', 'Marshall Thundering Herd',
    'Memphis Tigers', 'Navy Midshipmen', 'South Florida Bulls', 'Tulane Green Wave',
    'UNLV Rebels', 'Utah State Aggies',
  ],
  'NCAA Basketball': [
    'Alabama Crimson Tide', 'Arizona Wildcats', 'Arkansas Razorbacks', 'Auburn Tigers',
    'Baylor Bears', 'Butler Bulldogs', 'California Golden Bears', 'Cincinnati Bearcats',
    'Clemson Tigers', 'Colorado Buffaloes', 'Connecticut Huskies', 'Creighton Bluejays',
    'Duke Blue Devils', 'Florida Gators', 'Florida State Seminoles', 'Georgetown Hoyas',
    'Georgia Bulldogs', 'Georgia Tech Yellow Jackets', 'Gonzaga Bulldogs', 'Houston Cougars',
    'Illinois Fighting Illini', 'Indiana Hoosiers', 'Iowa Hawkeyes', 'Iowa State Cyclones',
    'Kansas Jayhawks', 'Kansas State Wildcats', 'Kentucky Wildcats', 'Louisville Cardinals',
    'LSU Tigers', 'Marquette Golden Eagles', 'Maryland Terrapins', 'Memphis Tigers',
    'Miami Hurricanes', 'Michigan Wolverines', 'Michigan State Spartans', 'Minnesota Golden Gophers',
    'Mississippi State Bulldogs', 'Missouri Tigers', 'NC State Wolfpack', 'Nebraska Cornhuskers',
    'North Carolina Tar Heels', 'Northwestern Wildcats', 'Notre Dame Fighting Irish',
    'Ohio State Buckeyes', 'Oklahoma State Cowboys', 'Ole Miss Rebels', 'Oregon Ducks',
    'Penn State Nittany Lions', 'Pittsburgh Panthers', 'Purdue Boilermakers',
    "Saint Mary's Gaels", 'San Diego State Aztecs', 'South Carolina Gamecocks',
    'Stanford Cardinal', 'Syracuse Orange', 'TCU Horned Frogs', 'Tennessee Volunteers',
    'Texas Longhorns', 'Texas A&M Aggies', 'Texas Tech Red Raiders', 'UCLA Bruins',
    'UNLV Rebels', 'USC Trojans', 'Utah Utes', 'Vanderbilt Commodores',
    'Villanova Wildcats', 'Virginia Cavaliers', 'Virginia Tech Hokies',
    'Wake Forest Demon Deacons', 'Washington Huskies', 'West Virginia Mountaineers',
    'Wisconsin Badgers', 'Xavier Musketeers',
  ],
}
